### ISSUE TITLE
Generating Documentation Using Github Pages Docs

### ISSUE THREAD

**Issue by chernykhSG** [tofu-tf/tofu#1232]
https://github.com/tofu-tf/tofu/blob/f4e5623f472e72285b2159e7c9a7b8e7480334ad/README.md?plain=1#L16  
the site is not working, you can use free documentation generation via github pages  https://docs.github.com/ru/pages/quickstart

**Comment by dos65** [comment]
Fixed - [tofu-tf.github.io/tofu/](https://tofu-tf.github.io/tofu/)
