### ISSUE TITLE
Support covariance in syntax

### ISSUE THREAD

**Issue by neko-kai** [tofu-tf/tofu#212]
i.e. for all syntax methods such as:

```scala
def flatTap[B](f: C => F[B])(implicit F: FlatMap[F]): F[C] = F.flatTap(fa)(f)
```

Replace with:

```scala
def flatTap[G[x] >: F[x], B](f: C => G[B])(implicit G: FlatMap[G]): G[C] = G.flatTap(fa)(f)
```

Motivation? The following works with covariant syntax:

```scala
Some(1).flatTap(_ => None)
```

But doesn't work with naive LEGACY syntax encodings.

**Comment by Odomontois** [comment]
Since this encoding is used in numerous places even for contravariant abstractions, I consider this issue mostly resolved
