### ISSUE TITLE
Sentry integration with logging

### ISSUE THREAD

**Issue by FunFunFine** [tofu-tf/tofu#238]
It is nice to have some way to integrate [sentry](https://sentry.io/for/scala/) with tofu logging, but I couldn't find any ways to do it. Is there any? 
If not, how can I help to implement this?

**Comment by Odomontois** [comment]
Yes, it would be a great new thing!

**Comment by Odomontois** [comment]
Close for now, feel free to reopen if new ideas or questions come up
