### ISSUE TITLE
Add implicit def for extracting subcontext from ReaderT

### ISSUE THREAD

**Issue by daron666** [tofu-tf/tofu#330]
Here is example. 
[Scactie](https://scastie.scala-lang.org/e2pEwCCVRPSe8BaWbaxnqg)

Given all the lenses (`A Contains B`) it would be nice to have implicit def that will extract subcontext like `ReaderT[M, A, *] => ReaderT[M, B, *]`

**Comment by Odomontois** [comment]
This is not possible. `ReaderT[M, A, *] => ReaderT[M, B, *]` requires at least `B => M[A]`  in the general case.
However supplied code would work with the presence of the following implicit 
```scala
  implicit def subcontext[A, B](implicit lens: A Contains B):  WithLocal[ReaderT[IO, A, *], B] =
      WithLocal[ReaderT[IO, A, *], A].subcontext(lens)
```

We may consider adding this to the instance chain for `Local`

**Comment by catostrophe** [comment]
If we add this, we will probably lose type inference for methods that allow one not to specify Ctx but to rely on the (unique-in-scope) `F HasContext Ctx` implicit.

**Comment by catostrophe** [comment]
Sorry, closed by mistake.

**Comment by Odomontois** [comment]
So it's not great in the current form. 
But I have that other idea of context-container usable with most of the reader construction to include batteries
