### ISSUE TITLE
Adopt scalafix

### ISSUE THREAD

**Issue by mehakun** [tofu-tf/tofu#674]
Since @FunFunFine is a user of scalafix and he volunteered to adopt it in project I created this issue to remind him or other volunteers:)

**Comment by mehakun** [comment]
Adoption means not only including scalafix in CI but also updating docs’s section about contributing

**Comment by Odomontois** [comment]
This is a nice issue, but since no discussion is going on currently, I'm closing for now on. Feel free to reopen when fresh ideas and contributing energy possess you.
