### ISSUE TITLE
Function to run CalcM for non nothing F[_], E types

### ISSUE THREAD

**Issue by sigevsky** [tofu-tf/tofu#708]
CalcM provides shortcut methods to evaluate itself for cases where E ~ Nothing type as well as for F ~ Nothing type. It would be nice to have a shortcut method to run it for both non-nothing E and F[_] types. That would be useful if one fancies using CalcM in place of ReaderT/ExceptT/StateT monad stack with IO playing role of an underlying effect.

**Comment by Odomontois** [comment]
Will push it, here the current workaround
```scala
  def tailrecEither[F[+_]: Monad, R, S1, S2, E, A](
      calc: CalcT[F, R, S1, S2, E, A]
  )(r: R, init: S1): F[(S2, Either[E, A])] =
    calc.step(r, init).tailRecM {
      case Ok(state, value)                    => Right((state, Right(value))).pure[F]
      case Error(state, err)                   => Right((state, Left(err))).pure[F]
      case wrap: Wrap[_, r, s, S2, x, E, m, A] =>
        wrap.inner.map(x => Left(wrap.cont.success(wrap.state, x).step(wrap.input, wrap.state)))
    }
 ```
