### ISSUE TITLE
Bury `simulacrum` finally

### ISSUE THREAD

**Issue by catostrophe** [tofu-tf/tofu#827]
`@typeclass` is a blocker for upgrading scalac to 2.13.7.

See: #815

**Comment by danslapman** [comment]
Maybe replace with https://github.com/typelevel/simulacrum-scalafix?

**Comment by Ssstlis** [comment]
These days I worked on bump stack and faced this problem. So, I think I can write some playground and create PR to resolve issue.

**Comment by Odomontois** [comment]
Closed in #948
