### ISSUE TITLE
Macro substitution of CE2Kernel does not work on Scala 2.12

### ISSUE THREAD

**Issue by nlchar** [tofu-tf/tofu#845]
### Problem
I am trying to migrate from `tofu 0.10.0` to `tofu 0.10.6` in my Scala `2.12.15` project. This cannot be achieved as [v0.10.4](https://github.com/tofu-tf/tofu/releases/tag/v0.10.4)  introduced the concept of so called Carriers that do not operate under Scala `2.12.*` properly. As a lot of productions still depend on that branch of Scala, I would like to report this case as a bug blocking migration to newer versions of tofu. 
### Example
To illustrate, I have isolated the issue in [a demo project](https://github.com/nlchar/tofu-interop-bug-example) where you can switch between Scala versions in `build.sbt` and see the difference.   
If the project is set up to work with Scala `2.13.*`, the supposed behaviour is achieved as it may be evidenced through the output of the program:
```
hello
tofu.interop.CE2Kernel$$anon$5@1de85f92
```
However, when switched back to Scala `2.12.*`, macro substitutions fail to manage implicit resolution correctly:
```
could not find implicit value for parameter e: tofu.Start[cats.effect.IO]
    val start = implicitly[Start[IO]]
```

**Comment by Odomontois** [comment]
I'll try to resolve it.

**Comment by Odomontois** [comment]
@nlchar 
It's vital to have `"-Ypartial-unification"` enabled in `scalacOptions` for the 2.12 project. Try to fix it as follows
https://github.com/nlchar/tofu-interop-bug-example/pull/1
Feel free to reopen this issue if the fix won't work
